### ISSUE TITLE
output intermediate results in a format that can be parsed

### ISSUE THREAD

**Issue by ffrohn** [aprove-developers/LoAT#1]
It is often the case that LoAT successfully simplifies a program, but hangs on one of the resulting limit problems. In these situations, it would be great to be able to invoke LoAT on the resulting transitions individually. Unfortunately, they are printed in a format that cannot be parsed back.

**Comment by mttnff** [comment]
To make use of the printed output, we would also need to allow division in the input file, as the simplified program often contains reals (e.g. `1/2*x^2-1/2*x`). We could add a flag to allow division, but we have to make it clear that LoAT is not sound for division (in general). Unfortunately, KoAT cannot be invoked on the simplified program for the same reason.

**Comment by mttnff** [comment]
Output of the simplified program (via a command line switch) is implemented in 2761d00f7672998ce739f425. We still need to address the issue of division.

**Comment by ffrohn** [comment]
I think having a flag to allow division in the input is a good idea. Maybe LoAT should just print a warning in the very beginning whenever this flag is enabled.

**Comment by mttnff** [comment]
I have added the following flags:

```
--print-simplified
--no-cost-check
--allow-division
--no-preprocessing
```

which allow to invoke LoAT on the intermediate result (the simplified program). The `--no-cost-check` is needed, as otherwise `cost >= 0` is added to the guard, which often is nonlinear. As the simplified program already ensures that costs are nonnegative, this is not a problem (but it is of course not sound to pass the flag in the general case). Preprocessing can also take some time, so if the program is already simplified, one might want to skip this step.
